# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://pmd.github.io
baseurl:
title: PMD
author: PMD
description: PMD is a source code analyzer. It finds unused variables, empty catch blocks, unnecessary object creation, and so forth.
keywords: PMD,Java,Salesforce.com Apex,Code Analyzer,Clean Code,Software Development
copyright: 'Copyright &copy; 2020 PMD. All Rights Reserved.'
credits: 'Credits: <a href="https://github.com/swcool/landing-page-theme">Landing Page Theme</a>, based on free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

exclude:
    - .gitignore
    - README.md
    - vendor

# to speed up local builds, exclude the following, too:
#    - 'pmd-5*'
#    - 'pmd-6*'

# ----------------------- #
#     PMD vars            #
# ----------------------- #
pmd:
  latestVersion: 6.42.0
  latestVersionDate: 29-January-2022
  downloads:
      - version: 6.41.0
        date: 27-November-2021
      - version: 6.40.0
        date: 30-October-2021
      - version: 6.39.0
        date: 25-September-2021

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/pmd/pmd
