# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://pmd.github.io
baseurl: ''
title: PMD
author: PMD
description: PMD is a source code analyzer. It finds unused variables, empty catch blocks, unnecessary object creation, and so forth.
keywords: PMD,Java,Salesforce.com Apex,Code Analyzer,Clean Code,Software Development
copyright: 'Copyright &copy; 2023 PMD. All Rights Reserved.'
credits: 'Credits: <a href="https://github.com/swcool/landing-page-theme">Landing Page Theme</a>, based on free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

exclude:
    - .gitignore
    - build-docs.sh
    - README.md
    - vendor
    - node_modules
    - scripts
    - package.json
    - package-lock.json

# ----------------------- #
#     PMD vars            #
# ----------------------- #
pmd:
  latestVersion: 7.0.0-rc4
  latestVersionDate: 30-September-2023
  downloads:
    - version: 7.0.0-rc3
      date: 30-May-2023
    - version: 7.0.0-rc2
      date: 29-April-2023
      distFormat: old
    - version: 7.0.0-rc1
      date: 25-March-2023
      distFormat: old
    - version: 6.55.0
      date: 25-February-2023
      distFormat: old

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/pmd/pmd
