# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://pmd.github.io
baseurl: ''
title: PMD
author: PMD
description: PMD is a source code analyzer. It finds unused variables, empty catch blocks, unnecessary object creation, and so forth.
keywords: PMD,Java,Salesforce.com Apex,Code Analyzer,Clean Code,Software Development
copyright: 'Copyright &copy; 2023 PMD. All Rights Reserved.'
credits: 'Credits: <a href="https://github.com/swcool/landing-page-theme">Landing Page Theme</a>, based on free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

exclude:
    - .gitignore
    - README.md
    - vendor

# to speed up local builds, exclude the following, too:
    - 'pmd-5*'
    - 'pmd-6*'

# ----------------------- #
#     PMD vars            #
# ----------------------- #
pmd:
  latestVersion: 6.54.0
  latestVersionDate: 28-January-2023
  downloads:
    - version: 6.53.0
      date: 31-December-2022
    - version: 6.52.0
      date: 26-November-2022
    - version: 6.51.0
      date: 29-October-2022

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/pmd/pmd
