# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://pmd.github.io
baseurl: ''
title: PMD
author: PMD
description: PMD is a source code analyzer. It finds unused variables, empty catch blocks, unnecessary object creation, and so forth.
keywords: PMD,Java,Salesforce.com Apex,Code Analyzer,Clean Code,Software Development
copyright: 'Copyright &copy; 2024 PMD. All Rights Reserved.'
credits: 'Credits: <a href="https://github.com/swcool/landing-page-theme">Landing Page Theme</a>, based on free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

exclude:
    - .gitignore
    - build-docs.sh
    - README.md
    - vendor
    - node_modules
    - scripts
    - package.json
    - package-lock.json

# ----------------------- #
#     PMD vars            #
# ----------------------- #
pmd:
  latestVersion: 7.8.0
  latestVersionDate: 29-November-2024
  downloads:
    - version: 7.7.0
      date: 25-October-2024
    - version: 7.6.0
      date: 27-September-2024
    - version: 7.5.0
      date: 30-August-2024

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: false
  # selectively enable kramdown parsing for block html elements with attribute 'markdown="block"'
  # see https://kramdown.gettalong.org/syntax.html
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/pmd/pmd
